Week10/cSharp/GuildBikes/GuildCars2/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bikes.data.ADO;
using bikes.data.Interfaces;
using bikes.data.Interfaces.Factories;
using bikes.models.Queries;
using bikes.models.Tables;
using bikes.models.VMs;
using GuildBikes.Utilities;

namespace GuildBikes.Controllers
{
    public class BikesController : Controller
    {
        // GET: Bikes
        public ActionResult Details(int id)
        {
            var repo = BikeRepoFactory.GetRepo();
            var model = repo.GetBikeDetails(id);

            return View(model);
        }

        public ActionResult Add()
        {
            BikeAddViewModel model = new BikeAddViewModel();

            model = ModelUtilities.InitBikeModel(model);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var BikeRepo = BikeRepoFactory.GetRepo();

            BikeEditViewModel model = new BikeEditViewModel();

            model = ModelUtilities.InitBikeModel(model);
            model.Bike = BikeRepo.GetById(id);


            ////TODO: When adding users, implement line below
            //if (model.Bike.UserId != AuthorizeUtilities.GetUserId(this))
            //{
            //    throw new Exception("Attempt to edit a listing you do not own! Naughty!");
            //}

            return View(model);
        }



        //[Authorize]
        [HttpPost]
        public ActionResult Add(BikeAddViewModel model)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                var repo = BikeRepoFactory.GetRepo();

                try
                {
                    //model.Bike.UserId = AuthorizeUtilities.GetUserId(this);

                    if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
                    {
                        var savepath = Server.MapPath("~/Images");

                        string fileName = Path.GetFileNameWithoutExtension(model.ImageUpload.FileName);
                        string extension = Path.GetExtension(model.ImageUpload.FileName);

                        var filePath = Path.Combine(savepath, fileName + extension);

                        int counter = 1;
                        while (System.IO.File.Exists(filePath))
                        {
                            filePath = Path.Combine(savepath, fileName + counter.ToString() + extension);
                            counter++;
                        }

                        model.ImageUpload.SaveAs(filePath);
                        model.Bike.BikePictName = Path.GetFileName(filePath);
                    }

                    repo.Insert(model.Bike);

                    //return RedirectToAction("Edit", new { id = model.Listing.ListingId });

                    //model = ModelUtilities.InitBikeModel(model);
                    //Inserted the line above to fix exception error after sucessfully adding
                    //a new bike.
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {

                model = ModelUtilities.InitBikeModel(model);

                //var statesRepo = StatesRepositoryFactory.GetRepository();
                //var bathroomRepo = BathroomTypesRepositoryFactory.GetRepository();

                //model.States = new SelectList(statesRepo.GetAll(), "StateId", "StateId");
                //model.BathroomTypes = new SelectList(bathroomRepo.GetAll(), "BathroomTypeId", "BathroomTypeName");

                return View(model);
            }
            model = ModelUtilities.InitBikeModel(model);
            // I added the line above as an intermedite step to fix an err:
            // Remove the line in future revisions
            return View(model);
            //// I added the line above as an intermedite step to fix the err:
            /// Not all paths return something.
            /// >>>---> Remove the line above soon
        }

//        [Authorize]
        [HttpPost]
        public ActionResult Edit(BikeEditViewModel model)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                var repo = BikeRepoFactory.GetRepo();

                try
                {
                    model.Bike.UserId = AuthorizeUtilities.GetUserId(this);
                    var oldListing = repo.GetById(model.Bike.BikeId);

                    if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
                    {
                        var savepath = Server.MapPath("~/Images");

                        string fileName = Path.GetFileNameWithoutExtension(model.ImageUpload.FileName);
                        string extension = Path.GetExtension(model.ImageUpload.FileName);

                        var filePath = Path.Combine(savepath, fileName + extension);

                        //Add 1 to files with the same name, or 2, 3, and so on.
                        int counter = 1;
                        while (System.IO.File.Exists(filePath))
                        {
                            filePath = Path.Combine(savepath, fileName + counter.ToString() + extension);
                            counter++;
                        }

                        model.ImageUpload.SaveAs(filePath);
                        model.Bike.BikePictName= Path.GetFileName(filePath);

                        // delete old file
                        var oldPath = Path.Combine(savepath, oldListing.BikePictName);
                        if (System.IO.File.Exists(oldPath))
                        {
                            System.IO.File.Delete(oldPath);
                        }
                    }
                    else
                    {
                        // they did not replace the old file, so keep the old file name
                        model.Bike.BikePictName = oldListing.BikePictName;
                    }

                    repo.Update(model.Bike);

                    return RedirectToAction("Edit", new { id = model.Bike.BikeId});
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                BikeTable crntBike = new BikeTable();
                crntBike = model.Bike;
                //Set model back to its initial state

                model = ModelUtilities.InitBikeModel(model);

                model.Bike = crntBike;
                return View(model);
            }
        }

    }
}

Week10/cSharp/GuildBikes/GuildCars2/Views/Bikes/Add.cshtml
@model bikes.models.VMs.BikeAddViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
        <h2>Add Bike</h2>
        @using (Html.BeginForm("Add", "Bikes", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmAddBike" }))
        {
            @Html.ValidationSummary()
            @*<div class="form-group">
                    <label>Nickname</label>
                    @Html.TextBoxFor(m => m.Bike., new { @class = "form-control" })
                </div>*@
            @*<div class="form-group">
                    <label>City</label>
                    @Html.TextBoxFor(m => m.Bike.City, new { @class = "form-control" })
                </div>*@
            <div class="form-group">
                <label>Make</label>
                @Html.DropDownListFor(m => m.Bike.BikeMakeId, Model.BikeMakes, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Model</label>
                @Html.DropDownListFor(m => m.Bike.BikeModelId, Model.BikeModels, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Year</label>
                @Html.DropDownListFor(m => m.Bike.BikeYear, Model.BikeYearItems, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Condition</label>
                @Html.DropDownListFor(m => m.Bike.BikeCondition, Model.ConditionItems, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>MSRP</label>
                @Html.TextBoxFor(m => m.Bike.BikeMsrp, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>List Price</label>
                @Html.TextBoxFor(m => m.Bike.BikeListPrice, new { @class = "form-control" })
            </div>
            @*<div class="form-group">
                    <label>Model Year</label>
                    @Html.DropDownListFor(m => m.Bike.BikeTrimColorId, Model.BikeColors, new { @class = "form-control" })
                </div>*@
            <div class="checkbox">
                <label>
                    @Html.CheckBoxFor(m => m.Bike.BikeIsNew) New
                </label>
            </div>

            <div class="form-group">
                <label>Frame Type</label>
                @Html.DropDownListFor(m => m.Bike.BikeFrameId, Model.BikeFrames, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Frame Color</label>
                @Html.DropDownListFor(m => m.Bike.BikeFrameColorId, Model.BikeColors, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Trim Color</label>
                @Html.DropDownListFor(m => m.Bike.BikeTrimColorId, Model.BikeColors, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Number of Gears</label>
                @Html.DropDownListFor(m => m.Bike.BikeNumGears, Model.BikeGearItems, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Serial Number</label>
                @Html.TextBoxFor(m => m.Bike.BikeSerialNum, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Description</label>
                @Html.TextAreaFor(m => m.Bike.BikeDescription, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Image</label>
                <input id="ImageUpload" name="ImageUpload" type="file" class="form-control" />
            </div>
            <button class="btn btn-primary">Save</button>
        }
    </div>
</div>


@section scripts
{
    <script>
        $(document).ready(function () {
            $('#frmAddBike').validate({
                rules: {
                    'Bike.BikeMsrp': {
                        required: true,
                        number: true,
                        min: 1
                    },
                    'Bike.BikeListPrice': {
                        required: true,
                        number: true,
                        min: 1
                    },
                    'Bike.BikeSerialNum': {
                        required: true
                    },
                }
            });
        });
    </script>
}

Week10/cSharp/GuildBikes/GuildCars2/Views/Bikes/Details.cshtml
@model bikes.models.Queries.InvDetailedItem

@{
    ViewBag.Title = "Details";
}

<h2>Bike Details</h2>

<div class="row">
    <div class="col-xs-12">
        <h3>Featured Bikes</h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4">
        <img src="@Url.Content("~/Images/" + Model.BikePictName)" height="300" width="300" />
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4">

        <table>
            <trbody>
                <tr>
                    <td>Body Style: @Model.BikeFrame</td>
                    <td>Frame Color: @Model.FrameColor</td>
                    <td>Sale Price: @Model.BikeListPrice</td>
                </tr>
                <tr>
                    <td>Gears: @Model.BikeNumGears</td>
                    <td>Condition: @Model.BikeCondition</td>
                    <td>MSRP: (Need to add)</td>
                </tr>
                <tr>
                    <td>Trim Color: @Model.TrimColor</td>
                    <td>Serial #:@Model.BikeSerialNum</td>
                </tr>
            </trbody>
        </table>
              
        <table>
            <trbody>
                <tr><td>@Model.BikeDescription</td></tr>
            </trbody>
        </table>

        <p></p>
        <form>
            @Html.ActionLink("Contact Us","Contact","Home",new { serialNo=Model.BikeSerialNum},new{@class="btn btn-primary"})
        </form> 

    </div>
</div>

Week10/cSharp/GuildBikes/GuildCars2/Views/Bikes/Edit.cshtml
@model bikes.models.VMs.BikeEditViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="row">
    <div class="col-xs-12>
        <h2>Edit Bike</h2>
        @using (Html.BeginForm("Edit", "Bikes", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmEditBike" }))
        {
            @Html.ValidationSummary()
            @Html.HiddenFor(m => m.Bike.BikeId)
            <div class="col-sm-12 col-md-6">
                <div class="form-group">
                    <label>Make</label>
                    @Html.DropDownListFor(m => m.Bike.BikeMakeId, Model.BikeMakes, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Model</label>
                    @Html.DropDownListFor(m => m.Bike.BikeModelId, Model.BikeModels, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Year</label>
                    @Html.DropDownListFor(m => m.Bike.BikeYear, Model.BikeYearItems, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Condition</label>
                    @Html.DropDownListFor(m => m.Bike.BikeCondition, Model.ConditionItems, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>MSRP</label>
                    @Html.TextBoxFor(m => m.Bike.BikeMsrp, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>List Price</label>
                    @Html.TextBoxFor(m => m.Bike.BikeListPrice, new { @class = "form-control" })
                </div>

                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(m => m.Bike.BikeIsNew) New
                    </label>
                </div>

                <div class="form-group">
                    <label>Frame Type</label>
                    @Html.DropDownListFor(m => m.Bike.BikeFrameId, Model.BikeFrames, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Frame Color</label>
                    @Html.DropDownListFor(m => m.Bike.BikeFrameColorId, Model.BikeColors, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Trim Color</label>
                    @Html.DropDownListFor(m => m.Bike.BikeTrimColorId, Model.BikeColors, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Number of Gears</label>
                    @Html.DropDownListFor(m => m.Bike.BikeNumGears, Model.BikeGearItems, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label>Serial Number</label>
                    @Html.TextBoxFor(m => m.Bike.BikeSerialNum, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Description</label>
                    @Html.TextAreaFor(m => m.Bike.BikeDescription, new { @class = "form-control" })
                </div>
                <button class="btn btn-primary">Save</button>
            </div>
            <div class="col-sm-12 col-md-6">
                <img src="@Url.Content("~/Images/" + Model.Bike.BikePictName)" height="300" width="300" />
                <div class="form-group">
                    <label>Replace Image</label>
                    <input id="ImageUpload" name="ImageUpload" type="file" class="form-control" />
                </div>
            </div>
        }
    </div>
</div>